#!/bin/bash

(cd shootout/go && make)
(cd shootout/java && make)
(cd shootout/mpl-cc && make)

NOW=$(date '+%y%m%d-%H%M%S')

# all of the extra arguments get sent to scripts/runcmds.py with $@ below
{ \
  shootout/java/gencmds; \
  shootout/go/gencmds; \
  shootout/mpl-cc/gencmds; \
} \
| scripts/runcmds.py --repeat 1 --output results/sort-$NOW $@
