#!/usr/bin/python

import sys
import json

def makeCmd(config, numProcs):
  return {'cmd': '/usr/bin/time -v ./msort.{} @mpl procs {} -- -N 100000000 -repeat 10 -warmup 5'.format(config, numProcs),
          'tag': 'sort-shootout',
          'config': config,
          'procs': numProcs,
          'cwd': 'shootout/mpl'}

procs = [1,10,20,30,40,50,60,70]

for p in procs:
  print(json.dumps(makeCmd("mpl", p)))

for p in procs:
  print(json.dumps(makeCmd("mpl-cc", p)))

mlton = \
  {'cmd': '/usr/bin/time -v ./msort.mlton -N 100000000 -repeat 10 -warmup 5',
   'tag': 'sort-shootout',
   'config': 'mlton',
   'procs': 1,
   'cwd': 'shootout/mpl'}

print(json.dumps(mlton))
