#!/usr/bin/python

import sys
import json

def makeCmd(numProcs):
  numa = ("" if numProcs == 1 else "numactl -i all -- ")
  return {'cmd': '/usr/bin/time -v {}./sort 100000000 {} 15 0'.format(numa, numProcs),
          'tag': 'sort-shootout',
          'config': 'go',
          'procs': numProcs,
          'cwd': 'shootout/go'}

procs = [1,10,20,30,40,50,60,70]

for p in procs:
  print(json.dumps(makeCmd(p)))
