#!/usr/bin/python

import sys
import json

def makeCmd(config, numProcs):
  return {'cmd': '/usr/bin/time -v ./msort.{} @mpl procs {} -- -N 100000000 -repeat 10 -warmup 5'.format(config, numProcs),
          'tag': 'sort-shootout',
          'config': config,
          'procs': numProcs,
          'cwd': 'shootout/mpl-cc'}

procs = [1,10,20,30,40,50,60,70]

for p in procs:
  print(json.dumps(makeCmd("mpl-cc", p)))
